# Generated by Django 5.0.4 on 2024-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_phone_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='comments',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='entrance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='intercom',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
