# Generated by Django 5.0.4 on 2024-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customeraddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
