# Generated by Django 5.0.4 on 2024-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customeraddress_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='apartment',
            field=models.TextField(blank=True, default='', max_length=15),
        ),
    ]
