# Generated by Django 5.0.4 on 2024-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customeraddress_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfullname',
            name='fullname',
            field=models.CharField(max_length=70),
        ),
    ]
