# Generated by Django 5.0.4 on 2024-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customerfullname_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfullname',
            name='fullname',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
