# Generated by Django 5.0.4 on 2024-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('on_the_way', 'On the Way')], default='on the way', max_length=20),
        ),
    ]
