# Generated by Django 5.0.4 on 2024-05-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
