# Generated by Django 5.0.4 on 2024-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_cost_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
