# Generated by Django 5.0.4 on 2024-05-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('доставлен', 'Заказ Доставлен'), ('отменён', 'Заказ Отменён'), ('в_пути', 'Заказ в Пути')], default='on the way', max_length=20),
        ),
    ]
