# Generated by Django 5.0.4 on 2024-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'Заказ Доставлен'), ('cancelled', 'Заказ Отменён'), ('on_the_way', 'Заказ в Пути')], default='on_the_way', max_length=20),
        ),
    ]
